Repository redBorder/redborder-documentation, pull requests merged in 2024-07, with the labels that each got.

#29 Improvement #17880 Change page color and text space
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: kind/documentation, size/S

#30 Feature/#17919 cluster installation
  docs/manager/redborder_basics/ch2_redborder_installation.es.md
  docs/manager/redborder_basics/ch2_redborder_installation.md
  docs/manager/redborder_basics/images/ch02_apply_conf.png
  docs/manager/redborder_basics/images/ch02_cancel_wizard.png
  docs/manager/redborder_basics/images/ch02_configure_wizard_start.png
  docs/manager/redborder_basics/images/ch02_end_installation.png
  docs/manager/redborder_basics/images/ch02_select_manage_interface.png
  docs/manager/redborder_basics/images/ch02_start_dns.png
  docs/manager/redborder_basics/images/ch02_start_network_conf.png
  docs/manager/redborder_basics/images/ch02_start_serf_configuration.png
  docs/manager/redborder_basics/images/ch02_sync_network_selection.png
Labels: bug, size/L, kind/feature

#21 Feature/ips installation
  README.md
  docs/.pages
  docs/ips/.pages
  docs/ips/IPS_basics/ch1_what_is_redborder.es.md
  docs/ips/IPS_basics/ch1_what_is_redborder.md
  docs/ips/IPS_basics/ch2_redborder_installation.es.md
  docs/ips/IPS_basics/ch2_redborder_installation.md
  docs/ips/IPS_basics/images/ch01_cloud_config.png
  docs/ips/IPS_basics/images/ch01_configure_wizard_start.png
  docs/ips/IPS_basics/images/ch01_end_registration.png
  docs/ips/IPS_basics/images/ch01_end_registration_manager.png
  docs/ips/IPS_basics/images/ch01_interface_naming_warn.png
  docs/ips/IPS_basics/images/ch01_network_device_mode.png
  docs/ips/IPS_basics/images/ch01_select_management_interface.png
  docs/ips/IPS_basics/images/ch02_apply_conf.png
  docs/ips/IPS_basics/images/ch02_blink.png
  docs/ips/IPS_basics/images/ch02_cancel_wizard_start.png
  docs/ips/IPS_basics/images/ch02_configure_segments.png
  docs/ips/IPS_basics/images/ch02_configure_wizard_start.png
  docs/ips/IPS_basics/images/ch02_delete_segment.png
  docs/ips/IPS_basics/images/ch02_finishing_configuration.png
  docs/ips/IPS_basics/images/ch02_img001.png
  docs/ips/IPS_basics/images/ch02_img002.png
  docs/ips/IPS_basics/images/ch02_img003.png
  docs/ips/IPS_basics/images/ch02_img004.png
  docs/ips/IPS_basics/images/ch02_img005.png
  docs/ips/IPS_basics/images/ch02_info_segments.png
  docs/ips/IPS_basics/images/ch02_ips_mode.png
  docs/ips/IPS_basics/images/ch02_new_segment.png
  docs/ips/IPS_basics/images/ch02_new_segment_in_list.png
  docs/ips/IPS_basics/images/ch02_pasword_config.png
  docs/ips/IPS_basics/images/ch02_sensor_reg.png
  docs/ips/platform_configurations/images/Claim_sensor.png
  docs/ips/platform_configurations/images/Claim_sensor_fields.png
  docs/ips/platform_configurations/images/Configuring_claimed_IPS.png
  docs/ips/platform_configurations/images/IPS_configured.png
  docs/ips/platform_configurations/images/IPS_manager_claimed.png
  docs/ips/platform_configurations/images/Unclaimed_loc.png
  docs/ips/platform_configurations/images/ips_unclaimed.png
  docs/ips/platform_configurations/images/journal_register.png
  docs/ips/platform_configurations/images/select_uuid.png
  docs/ips/platform_configurations/ips_sensor.es.md
  docs/ips/platform_configurations/ips_sensor.md
  docs/manager/redborder_basics/ch2_redborder_installation.es.md
  docs/manager/redborder_basics/ch2_redborder_installation.md
Labels: documentation, size/XL, kind/feature

#33 Feature/#17648 ips installation
  docs/ips/IPS_basics/ch1_what_is_redborder.es.md
  docs/ips/IPS_basics/ch1_what_is_redborder.md
  docs/ips/IPS_basics/ch2_redborder_installation.es.md
  docs/ips/IPS_basics/ch2_redborder_installation.md
Labels: kind/documentation, size/M

#28 Feature/#17726 Integration with OTRS
  build_pdf/getting_started_book/en.yml
  build_pdf/getting_started_book/es.yml
  docs/guides/.pages
  docs/guides/integrations/images/otrs_step_1.png
  docs/guides/integrations/images/otrs_step_10.png
  docs/guides/integrations/images/otrs_step_2.png
  docs/guides/integrations/images/otrs_step_3.png
  docs/guides/integrations/images/otrs_step_4.png
  docs/guides/integrations/images/otrs_step_5.png
  docs/guides/integrations/images/otrs_step_6.png
  docs/guides/integrations/images/otrs_step_7.png
  docs/guides/integrations/images/otrs_step_8.png
  docs/guides/integrations/images/otrs_step_9.png
  docs/guides/integrations/otrs.es.md
  docs/guides/integrations/otrs.md
  docs/manager/.pages
Labels: documentation, size/L, kind/feature

#24 improvement/#17639_update_reports_doc
  docs/manager/redborder_basics/ch4_1_modules.es.md
  docs/manager/redborder_basics/ch4_1_modules.md
  docs/manager/redborder_basics/images/ch04_img009-en.png
  docs/manager/redborder_basics/images/ch04_img009.png
  docs/manager/redborder_basics/images/ch04_img049-en.png
  docs/manager/redborder_basics/images/ch04_img052-en.png
  docs/manager/redborder_basics/images/ch04_img052.png
  docs/manager/redborder_basics/images/ch04_img053-en.png
  docs/manager/redborder_basics/images/ch04_img053.png
  docs/manager/redborder_basics/images/ch04_img054-en.png
  docs/manager/redborder_basics/images/ch04_img054.png
  docs/manager/redborder_basics/images/ch04_img055.png
Labels: kind/documentation, size/M

#26 #17857 Proxy migration
  docs/.pages
  docs/proxy/.pages
  docs/proxy/index.es.md
  docs/proxy/index.md
  docs/proxy/platform_configurations/ch1_proxy_installation.es.md
  docs/proxy/platform_configurations/ch1_proxy_installation.md
  docs/proxy/platform_configurations/images/Claim_sensor.png
  docs/proxy/platform_configurations/images/Claim_sensor_fields.png
  docs/proxy/platform_configurations/images/Configuring_claimed.png
  docs/proxy/platform_configurations/images/Proxy_configured.png
  docs/proxy/platform_configurations/images/Select_management.png
  docs/proxy/platform_configurations/images/Unclaimed_loc.png
  docs/proxy/platform_configurations/images/ch01_apply_conf.png
  docs/proxy/platform_configurations/images/ch01_applying_conf.png
  docs/proxy/platform_configurations/images/ch01_cloud_config.png
  docs/proxy/platform_configurations/images/ch01_end_registration.png
  docs/proxy/platform_configurations/images/ch01_img007.png
  docs/proxy/platform_configurations/images/ch01_img008.png
  docs/proxy/platform_configurations/images/ch01_img009.png
  docs/proxy/platform_configurations/images/ch01_img010.png
  docs/proxy/platform_configurations/images/ch01_img011.png
  docs/proxy/platform_configurations/images/ch01_img012.png
  docs/proxy/platform_configurations/images/ch01_img013.png
  docs/proxy/platform_configurations/images/ch02_configure_wizard_start.png
  docs/proxy/platform_configurations/images/journal_register.png
  docs/proxy/platform_configurations/images/proxy_unclaimed.png
  docs/proxy/platform_configurations/images/select_uuid.png
  docs/proxy/platform_configurations/proxy_sensor.es.md
  docs/proxy/platform_configurations/proxy_sensor.md
  docs/proxy/proxy_basics/index.es.md
  docs/proxy/redborder_basics/ch1_proxy_installation.md
Labels: good first issue, kind/documentation, size/XL

#32 Feature/#17728 integration with saml
  build_pdf/getting_started_book/en.yml
  build_pdf/getting_started_book/es.yml
  docs/guides/integrations/images/sso_config.png
  docs/guides/integrations/images/sso_login.png
  docs/guides/integrations/sso.es.md
  docs/guides/integrations/sso.md
  mkdocs.yml
Labels: size/L, kind/feature

#42 fixing warnings about deprecation and moved images
  docs/proxy/proxy_basics/index.es.md
  docs/proxy/redborder_basics/ch1_proxy_installation.md
  mkdocs.yml
Labels: bug, duplicate, good first issue, size/S

#44 update yamls with new paths. Fix one spanish to english.
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
Labels: enhancement, size/XS

#45 Improvement/#18124 add ips and proxy to pdf gen
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
Labels: enhancement, size/XS, kind/feature

#46 Add Documentation about GLPI Integration
  docs/guides/integrations/glpi.es.md
  docs/guides/integrations/glpi.md
  docs/guides/integrations/images/glpi_step_1.png
  docs/guides/integrations/images/glpi_step_2.png
Labels: kind/documentation, size/M
