Repository redBorder/redborder-documentation, pull requests merged in 2024-04, with the labels that each got.

#10 Feature #16886 Add chapter 4.1 and 4.2: Modules, options and menu
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
  docs/chapters/redborder_basics/ch4_1_modules.es.md
  docs/chapters/redborder_basics/ch4_1_modules.md
  docs/chapters/redborder_basics/ch4_2_modules_menu_options.es.md
  docs/chapters/redborder_basics/ch4_2_modules_menu_options.md
  docs/chapters/redborder_basics/images/ch04_img001.png
  docs/chapters/redborder_basics/images/ch04_img002.png
  docs/chapters/redborder_basics/images/ch04_img003.png
  docs/chapters/redborder_basics/images/ch04_img004.png
  docs/chapters/redborder_basics/images/ch04_img005.png
  docs/chapters/redborder_basics/images/ch04_img006.png
  docs/chapters/redborder_basics/images/ch04_img007.png
  docs/chapters/redborder_basics/images/ch04_img008.png
  docs/chapters/redborder_basics/images/ch04_img009.png
  docs/chapters/redborder_basics/images/ch04_img010.png
  docs/chapters/redborder_basics/images/ch04_img011.png
  docs/chapters/redborder_basics/images/ch04_img012.png
  docs/chapters/redborder_basics/images/ch04_img013.png
  docs/chapters/redborder_basics/images/ch04_img014.png
  docs/chapters/redborder_basics/images/ch04_img015.png
  docs/chapters/redborder_basics/images/ch04_img016.png
  docs/chapters/redborder_basics/images/ch04_img017.png
  docs/chapters/redborder_basics/images/ch04_img018.png
  docs/chapters/redborder_basics/images/ch04_img019.png
  docs/chapters/redborder_basics/images/ch04_img020.png
  docs/chapters/redborder_basics/images/ch04_img021.png
  docs/chapters/redborder_basics/images/ch04_img022.png
  docs/chapters/redborder_basics/images/ch04_img023.png
  docs/chapters/redborder_basics/images/ch04_img024.png
  docs/chapters/redborder_basics/images/ch04_img025.png
  docs/chapters/redborder_basics/images/ch04_img026.png
  docs/chapters/redborder_basics/images/ch04_img027.png
  docs/chapters/redborder_basics/images/ch04_img028.png
  docs/chapters/redborder_basics/images/ch04_img029.png
Labels: documentation, size/XL, kind/feature

#11 Bugfix/#17034 404 in home doc
  README.md
  docs/CNAME
Labels: bug, good first issue, kind/documentation, size/XS

#13 Feature #17057 Migrate C6 chapter 4.5 of manual to NG docs website
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
  docs/chapters/more_in_detail/ch4_5_views.es.md
  docs/chapters/more_in_detail/ch4_5_views.md
  docs/chapters/more_in_detail/images/ch04_img042.png
  docs/chapters/more_in_detail/images/ch04_img043.png
  docs/chapters/more_in_detail/images/ch04_img044.png
  docs/chapters/more_in_detail/images/ch04_img045.png
  docs/chapters/more_in_detail/images/ch04_img046.png
  docs/chapters/more_in_detail/images/ch04_img047.png
Labels: kind/documentation, size/L

#15 Improvement #17094 Add a better home page
  docs/index.es.md
  docs/index.md
Labels: kind/documentation, size/M

#16 Feature/#17099 Migrate C6 chapter 4.6 to 4.10 of manual to NG docs website
  docs/index.es.md
  docs/manager/redborder_basics/ch2_redborder_installation.es.md
  docs/manager/redborder_basics/ch4_2_modules_menu_options.es.md
  docs/manager/redborder_basics/ch4_2_modules_menu_options.md
  docs/manager/redborder_basics/images/ch04_img022.png
  docs/manager/redborder_basics/images/ch06_img001.png
Labels: kind/documentation, size/L
