Repository redBorder/redborder-documentation, pull requests merged in 2024-10, with the labels that each got.

#53 Bugfix/#18123 delete duplicated chapter
  docs/proxy/platform_configurations/images/proxy_add_sensor.png
  docs/proxy/platform_configurations/proxy_sensor.es.md
  docs/proxy/platform_configurations/proxy_sensor.md
  docs/proxy/proxy_basics/index.es.md
  docs/proxy/redborder_basics/ch1_proxy_installation.md
Labels: size/M, kind/bug

#59 hide all malware references (at least in text)
  docs/ips/IPS_basics/ch1_what_is_redborder.es.md
  docs/ips/IPS_basics/ch1_what_is_redborder.md
  docs/manager/more_in_detail/ch4_5_views.es.md
  docs/manager/more_in_detail/ch4_5_views.md
  docs/manager/more_in_detail/ch5_dashboards.es.md
  docs/manager/more_in_detail/ch5_dashboards.md
  docs/manager/redborder_basics/ch1_what_is_redborder.es.md
  docs/manager/redborder_basics/ch1_what_is_redborder.md
  docs/manager/redborder_basics/ch4_1_modules.es.md
  docs/manager/redborder_basics/ch4_1_modules.md
  docs/manager/redborder_basics/ch4_2_modules_menu_options.es.md
  docs/manager/redborder_basics/ch4_2_modules_menu_options.md
Labels: documentation, size/L, kind/bug

#64 Bugfix #19215 Don't say it's easy to install
  docs/manager/redborder_basics/ch2_redborder_installation.es.md
  docs/manager/redborder_basics/ch2_redborder_installation.md
Labels: size/XS, kind/bug

#39 Feature #17933 Migrate API documentation
  .gitignore
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
  docs/manager/.pages
  docs/manager/redborder_api/ch10_introduction.es.md
  docs/manager/redborder_api/ch10_introduction.md
  docs/manager/redborder_api/ch10_use_examples.es.md
  docs/manager/redborder_api/ch10_use_examples.md
  docs/manager/redborder_api/ch11_model_sharing.es.md
  docs/manager/redborder_api/ch11_model_sharing.md
  docs/manager/redborder_api/images/ch10_img001.png
  docs/manager/redborder_api/sample_json/create_domain.json
  docs/manager/redborder_api/sample_json/create_sensor.json
  docs/manager/redborder_api/sample_json/debug
  docs/manager/redborder_api/sample_json/rb_event.json
  docs/manager/redborder_api/sample_json/rb_flow_00.json
  docs/manager/redborder_api/sample_json/rb_flow_01.json
  docs/manager/redborder_api/sample_json/rb_monitor.json
Labels: kind/documentation, kind/feature

#50 Feature/#18221 ips sensor policies
  docs/ips/platform_configurations/ch3_ips_sensor.es.md
  docs/ips/platform_configurations/ch3_ips_sensor.md
  docs/ips/platform_configurations/ch4_policies.es.md
  docs/ips/platform_configurations/ch4_policies.md
  docs/ips/platform_configurations/images/Groups.png
  docs/ips/platform_configurations/images/apply_conf.png
  docs/ips/platform_configurations/images/color_map.png
  docs/ips/platform_configurations/images/country.png
  docs/ips/platform_configurations/images/exporter_details.png
  docs/ips/platform_configurations/images/ips_exporter.png
  docs/ips/platform_configurations/images/ips_monitor.png
  docs/ips/platform_configurations/images/ips_properties.png
  docs/ips/platform_configurations/images/map.png
  docs/ips/platform_configurations/images/rep_pol.png
  docs/ips/platform_configurations/images/rules_expanded.png
  docs/ips/platform_configurations/images/sig_pol.png
  docs/ips/platform_configurations/images/signature_policy_detail.png
  docs/ips/platform_configurations/images/signature_policy_view.png
  docs/ips/platform_configurations/images/snort_rule_select.png
Labels: documentation, help wanted, size/L

#56 Feature/#18101 add incidents
  build_pdf/redborder_manual_book/en.yml
  build_pdf/redborder_manual_book/es.yml
  docs/guides/use_cases/ch9_detect_eternalblue.es.md
  docs/guides/use_cases/ch9_detect_eternalblue.md
  docs/guides/use_cases/images/eternalblue_affected_notes.png
  docs/guides/use_cases/images/eternalblue_confirm_notes.png
  docs/guides/use_cases/images/eternalblue_first_notes.png
  docs/guides/use_cases/images/eternalblue_incident_list.png
  docs/guides/use_cases/images/eternalblue_incident_overview.png
  docs/guides/use_cases/images/eternalblue_incident_response.png
  docs/index.es.md
  docs/index.md
  docs/manager/more_in_detail/ch5_1_incidents.es.md
  docs/manager/more_in_detail/ch5_1_incidents.md
  docs/manager/more_in_detail/images/ch05_1_add_note.png
  docs/manager/more_in_detail/images/ch05_1_detection.png
  docs/manager/more_in_detail/images/ch05_1_incident_detail.png
  docs/manager/more_in_detail/images/ch05_1_incident_sum.png
  docs/manager/more_in_detail/images/ch05_1_incidents_view.png
  docs/manager/more_in_detail/images/ch05_1_overview.png
  docs/manager/more_in_detail/images/ch05_1_response.png
  docs/manager/more_in_detail/images/ch05_1_worklog.png
  docs/manager/redborder_basics/ch3_web_platform.es.md
  docs/manager/redborder_basics/ch3_web_platform.md
Labels: size/L, kind/feature

#61 Feature/#18124 autobuild pdf
  .github/workflows/create-pdf.yml
  LICENSE
  build_pdf/README.MD
  build_pdf/build_base.yml
Labels: documentation, question, size/M, kind/feature

#60 Improvement/#18215 add mitre
  docs/manager/platform_configurations/ch7_tools_and_admin.es.md
  docs/manager/platform_configurations/ch7_tools_and_admin.md
  docs/manager/platform_configurations/images/mitre_empty.png
  docs/manager/platform_configurations/images/mitre_matrix.png
  docs/manager/platform_configurations/images/mitre_tactics.png
Labels: documentation, size/L, kind/feature
